name: test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10
          cache: 'poetry'
      - name: Create venv
        shell: bash
        run: python -m venv .venv
      - name: Install dependencies
        shell: bash
        run: poetry install
      - name: Run tests
        run: mypy project

